table DimDate
	lineageTag: 30629ab5-71fa-45f1-ab6a-a8b7b07b06b7

	column Date
		dataType: dateTime
		formatString: General Date
		lineageTag: 6bd550fb-11aa-4f5a-9130-8819df4895b1
		summarizeBy: none
		sourceColumn: Date

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		formatString: 0
		lineageTag: fe4a545a-5b82-4ec7-948d-21fa0203e68e
		summarizeBy: none
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: 5274884b-28a1-4eea-9c09-74ca969b73f7
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column MonthNumber
		dataType: int64
		formatString: 0
		lineageTag: df310b2d-ec86-423f-9750-5540860ea719
		summarizeBy: none
		sourceColumn: MonthNumber

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: string
		lineageTag: 6787e156-d3b4-4899-8b26-7595638a9615
		summarizeBy: none
		sortByColumn: MonthNumber
		sourceColumn: Month

		annotation SummarizationSetBy = Automatic

	column YearMonth
		dataType: dateTime
		formatString: Long Date
		lineageTag: 44cf159a-a64d-406e-bce3-a4161b44addf
		summarizeBy: none
		sourceColumn: YearMonth

		variation Variation
			isDefault
			relationship: 3efc4ac8-2f89-47e0-8821-cb5377b36510
			defaultHierarchy: LocalDateTable_d144b7be-81b9-45ed-92e0-625a0ff4a3db.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column WeekNumber
		dataType: int64
		formatString: 0
		lineageTag: 78e60da5-27e0-4f42-a054-5eacdc79f90d
		summarizeBy: none
		sourceColumn: WeekNumber

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: string
		lineageTag: 788004e8-5ba5-4d72-bad4-172a574af760
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	partition DimDate = m
		mode: import
		source =
				let
				  Source = Excel.Workbook(File.Contents("C:\work\DQ\pbi\data\power_bi_jira_defect_test_data.xlsx"), null, true),
				  #"Navigation 1" = Source{[Item = "DimDate", Kind = "Sheet"]}[Data],
				  #"Promoted headers" = Table.PromoteHeaders(#"Navigation 1", [PromoteAllScalars = true]),
				  #"Changed column type" = Table.TransformColumnTypes(#"Promoted headers", {{"Date", type date}, {"Year", Int64.Type}, {"Quarter", type text}, {"MonthNumber", Int64.Type}, {"Month", type text}, {"YearMonth", type date}, {"WeekNumber", Int64.Type}, {"DayOfWeek", type text}})
				in
				  #"Changed column type"

	annotation PBI_ResultType = Table

