table DimProject
	lineageTag: e5df3967-85aa-4f9a-a046-64e3af8ac664

	column ProjectCode
		dataType: string
		lineageTag: 8412bc04-0ef3-4baa-a850-37f117fc21f1
		summarizeBy: none
		sourceColumn: ProjectCode

		annotation SummarizationSetBy = Automatic

	column ProjectName
		dataType: string
		lineageTag: 1c9027da-bd6f-4b40-a0c8-f67097224f52
		summarizeBy: none
		sourceColumn: ProjectName

		annotation SummarizationSetBy = Automatic

	column Domain
		dataType: string
		lineageTag: aa78a663-4906-4cf4-acdd-8049170430b0
		summarizeBy: none
		sourceColumn: Domain

		annotation SummarizationSetBy = Automatic

	column Region
		dataType: string
		lineageTag: 2026807f-eee4-4ee7-8f57-a6015e7a0d61
		summarizeBy: none
		sourceColumn: Region

		annotation SummarizationSetBy = Automatic

	partition DimProject = m
		mode: import
		source =
				let
				  Source = Excel.Workbook(File.Contents("C:\work\DQ\pbi\data\power_bi_jira_defect_test_data.xlsx"), null, true),
				  #"Navigation 1" = Source{[Item = "DimProject", Kind = "Sheet"]}[Data],
				  #"Promoted headers" = Table.PromoteHeaders(#"Navigation 1", [PromoteAllScalars = true]),
				  #"Changed column type" = Table.TransformColumnTypes(#"Promoted headers", {{"ProjectCode", type text}, {"ProjectName", type text}, {"Domain", type text}, {"Region", type text}})
				in
				  #"Changed column type"

	annotation PBI_ResultType = Table

