table DimStatus
	lineageTag: 799c1378-6a97-45c1-966b-762cf35cb805

	column Status
		dataType: string
		lineageTag: 6077b95b-afdf-44fb-a169-ec2fc1e29a3d
		summarizeBy: none
		sourceColumn: Status

		annotation SummarizationSetBy = Automatic

	column IsOpen
		dataType: int64
		formatString: 0
		lineageTag: 00b486ca-d360-4fca-9233-8451f45732dc
		summarizeBy: none
		sourceColumn: IsOpen

		annotation SummarizationSetBy = Automatic

	column IsClosed
		dataType: int64
		formatString: 0
		lineageTag: 4547b06c-db32-4e9e-bfb8-17bb13e7e7d6
		summarizeBy: none
		sourceColumn: IsClosed

		annotation SummarizationSetBy = Automatic

	partition DimStatus = m
		mode: import
		source =
				let
				  Source = Excel.Workbook(File.Contents("C:\work\DQ\pbi\data\power_bi_jira_defect_test_data.xlsx"), null, true),
				  #"Navigation 1" = Source{[Item = "DimStatus", Kind = "Sheet"]}[Data],
				  #"Promoted headers" = Table.PromoteHeaders(#"Navigation 1", [PromoteAllScalars = true]),
				  #"Changed column type" = Table.TransformColumnTypes(#"Promoted headers", {{"Status", type text}, {"IsOpen", Int64.Type}, {"IsClosed", Int64.Type}})
				in
				  #"Changed column type"

	annotation PBI_ResultType = Table

