table ExpectedKPIs
	lineageTag: 6a596dae-9d0a-4861-bb16-280a5afae804

	column Metric
		dataType: string
		lineageTag: 38b430c0-9837-4524-a844-c4f45210b009
		summarizeBy: none
		sourceColumn: Metric

		annotation SummarizationSetBy = Automatic

	column ExpectedValue
		dataType: int64
		formatString: 0
		lineageTag: 1e5d3474-0d54-4a69-80c9-75ca507ab9b3
		summarizeBy: sum
		sourceColumn: ExpectedValue

		annotation SummarizationSetBy = Automatic

	partition ExpectedKPIs = m
		mode: import
		source =
				let
				  Source = Excel.Workbook(File.Contents("C:\work\DQ\pbi\data\power_bi_jira_defect_test_data.xlsx"), null, true),
				  #"Navigation 1" = Source{[Item = "ExpectedKPIs", Kind = "Sheet"]}[Data],
				  #"Promoted headers" = Table.PromoteHeaders(#"Navigation 1", [PromoteAllScalars = true]),
				  #"Changed column type" = Table.TransformColumnTypes(#"Promoted headers", {{"Metric", type text}, {"ExpectedValue", Int64.Type}})
				in
				  #"Changed column type"

	annotation PBI_ResultType = Table

