table FactDefects
	lineageTag: a9088d2a-3c53-460f-be9e-d36b6264b5d7

	column IssueKey
		dataType: string
		lineageTag: 93c8cede-b7e5-4e4b-bbce-f546afbc4c9a
		summarizeBy: none
		sourceColumn: IssueKey

		annotation SummarizationSetBy = Automatic

	column ProjectCode
		dataType: string
		lineageTag: 221817c9-09c6-45e1-91ce-73c7c769c858
		summarizeBy: none
		sourceColumn: ProjectCode

		annotation SummarizationSetBy = Automatic

	column ProjectName
		dataType: string
		lineageTag: 2dba43ca-1d88-4d7f-ad77-26f26b70b325
		summarizeBy: none
		sourceColumn: ProjectName

		annotation SummarizationSetBy = Automatic

	column IssueType
		dataType: string
		lineageTag: 7a3a8abb-474c-4c05-a1a9-18242b66a706
		summarizeBy: none
		sourceColumn: IssueType

		annotation SummarizationSetBy = Automatic

	column Priority
		dataType: string
		lineageTag: 636cba27-1fa6-44d1-8178-5793e023901d
		summarizeBy: none
		sourceColumn: Priority

		annotation SummarizationSetBy = Automatic

	column Status
		dataType: string
		lineageTag: c851e9d3-ee30-4c07-a7de-c5fcf182d89b
		summarizeBy: none
		sourceColumn: Status

		annotation SummarizationSetBy = Automatic

	column Summary
		dataType: string
		lineageTag: c14691d0-c191-43a9-ad0b-dc4e286be2f2
		summarizeBy: none
		sourceColumn: Summary

		annotation SummarizationSetBy = Automatic

	column Component
		dataType: string
		lineageTag: a1f896cc-c830-46f1-a981-b1cc3a9b72a4
		summarizeBy: none
		sourceColumn: Component

		annotation SummarizationSetBy = Automatic

	column Environment
		dataType: string
		lineageTag: aecd3415-f9e0-4002-aa53-2610fdfd5130
		summarizeBy: none
		sourceColumn: Environment

		annotation SummarizationSetBy = Automatic

	column CreatedDate
		dataType: dateTime
		formatString: General Date
		lineageTag: 182e955b-52c0-49a3-a438-662623bc651e
		summarizeBy: none
		sourceColumn: CreatedDate

		annotation SummarizationSetBy = Automatic

	column UpdatedDate
		dataType: dateTime
		formatString: General Date
		lineageTag: 022462d2-fa26-4179-bedf-76bc13cf27ae
		summarizeBy: none
		sourceColumn: UpdatedDate

		annotation SummarizationSetBy = Automatic

	column ResolvedDate
		dataType: dateTime
		formatString: General Date
		lineageTag: f459a1bf-45ea-475a-8e45-ad4c6e7c34e1
		summarizeBy: none
		sourceColumn: ResolvedDate

		annotation SummarizationSetBy = Automatic

	column Assignee
		dataType: string
		lineageTag: 55685363-a3f2-4dce-a419-3dfca53122ab
		summarizeBy: none
		sourceColumn: Assignee

		annotation SummarizationSetBy = Automatic

	column Reporter
		dataType: string
		lineageTag: 3cfaa0c4-0749-42ca-b819-a4c2f98aaa23
		summarizeBy: none
		sourceColumn: Reporter

		annotation SummarizationSetBy = Automatic

	column CustomerImpact
		dataType: string
		lineageTag: 5679d146-5069-4618-afd9-de7f38d5e393
		summarizeBy: none
		sourceColumn: CustomerImpact

		annotation SummarizationSetBy = Automatic

	column SLATargetDays
		dataType: int64
		formatString: 0
		lineageTag: a794b5f6-e249-4942-817d-9ad28bfa3917
		summarizeBy: sum
		sourceColumn: SLATargetDays

		annotation SummarizationSetBy = Automatic

	column AgeDays
		dataType: int64
		formatString: 0
		lineageTag: 76c2ee55-15c0-40ea-9d73-d54fb592af94
		summarizeBy: sum
		sourceColumn: AgeDays

		annotation SummarizationSetBy = Automatic

	column SLABreached
		dataType: string
		lineageTag: 3b812df7-32a5-434f-8cde-4f14226b01d5
		summarizeBy: none
		sourceColumn: SLABreached

		annotation SummarizationSetBy = Automatic

	column OpenFlag
		dataType: int64
		formatString: 0
		lineageTag: fc1ab63c-0304-433d-845a-d01c07cd540d
		summarizeBy: sum
		sourceColumn: OpenFlag

		annotation SummarizationSetBy = Automatic

	column ClosedFlag
		dataType: int64
		formatString: 0
		lineageTag: edd3aaf9-dfd5-4f38-9d55-6cb20058b96e
		summarizeBy: sum
		sourceColumn: ClosedFlag

		annotation SummarizationSetBy = Automatic

	measure 'Total Defects' = DISTINCTCOUNT(FactDefects[IssueKey])
	measure 'Open Defects' = SUM(FactDefects[OpenFlag])
	measure 'Closed Defects' = SUM(FactDefects[ClosedFlag])

	partition FactDefects = m
		mode: import
		source =
				let
				  Source = Excel.Workbook(File.Contents("C:\work\DQ\pbi\data\power_bi_jira_defect_test_data.xlsx"), null, true),
				  #"Navigation 1" = Source{[Item = "FactDefects", Kind = "Sheet"]}[Data],
				  #"Promoted headers" = Table.PromoteHeaders(#"Navigation 1", [PromoteAllScalars = true]),
				  #"Changed column type" = Table.TransformColumnTypes(#"Promoted headers", {{"IssueKey", type text}, {"ProjectCode", type text}, {"ProjectName", type text}, {"IssueType", type text}, {"Priority", type text}, {"Status", type text}, {"Summary", type text}, {"Component", type text}, {"Environment", type text}, {"CreatedDate", type date}, {"UpdatedDate", type date}, {"ResolvedDate", type date}, {"Assignee", type text}, {"Reporter", type text}, {"CustomerImpact", type text}, {"SLATargetDays", Int64.Type}, {"AgeDays", Int64.Type}, {"SLABreached", type text}, {"OpenFlag", Int64.Type}, {"ClosedFlag", Int64.Type}})
				in
				  #"Changed column type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

